const dummyData =[
    {   
        "id" : 1,
        "carouselId" : "itemOne",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4500,
        "name" : "Pan Pacific",
        "availableFrom": "01.10.2020",
        "minimumStay" : "2 months",
    },
    {   
        "id" : 2,
        "carouselId" : "itemTwo",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4900,
        "name" : "Holy SIde",
        "availableFrom": "10.11.2020",
        "minimumStay" : "3 months",
    },
    {   
        "id" : 3,
        "carouselId" : "itemThree",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 5100,
        "name" : "Sheraton Villa",
        "availableFrom": "12.11.2020",
        "minimumStay" : "2 months",
    },
    {   
        "id" : 4,
        "carouselId" : "itemFour",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4700,
        "name" : "Rose View",
        "availableFrom": "01.10.2021",
        "minimumStay" : "4 months",
    },
    {   
        "id" : 5,
        "carouselId" : "itemFive",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4550,
        "name" : "Star Stay",
        "availableFrom": "02.11.2021",
        "minimumStay" : "1 months",
    },
    {   
        "id" : 6,
        "carouselId" : "itemSix",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4850,
        "name" : "Ambrosia House",
        "availableFrom": "10.05.2021",
        "minimumStay" : "2 months",
    },
    {   
        "id" : 7,
        "carouselId" : "itemSeven",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4900,
        "name" : "Raintree Villa",
        "availableFrom": "04.03.2021",
        "minimumStay" : "5 months",
    },
    {   
        "id" : 8,
        "carouselId" : "itemEight",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 5400,
        "name" : "Radison blu",
        "availableFrom": "01.03.2021",
        "minimumStay" : "4 months",
    },
    {   
        "id" : 9,
        "carouselId" : "itemNine",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4600,
        "name" : "Gulshan Cottage",
        "availableFrom": "02.03.2021",
        "minimumStay" : "1 months",
    },
    {   
        "id" : 10,
        "carouselId" : "itemTen",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4200,
        "name" : "Khan Cottage",
        "availableFrom": "04.03.2021",
        "minimumStay" : "4 months",
    },
    {   
        "id" : 11,
        "carouselId" : "itemEleven",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 4100,
        "name" : "Surma Cottage",
        "availableFrom": "11.02.2021",
        "minimumStay" : "3 months",
    },
    {   
        "id" : 12,
        "carouselId" : "itemTwelve",
        "img1" : "https://i.ibb.co/PTz9Kpv/property-01.jpg",
        "img2" : "https://i.ibb.co/n09tDkS/property-03.jpg",
        "img3" : "https://i.ibb.co/d6GFdVj/property-04.jpg",
        "price": 5600,
        "name" : "Grand Cottage",
        "availableFrom": "05.05.2021",
        "minimumStay" : "5 months",
    }
]

export default dummyData;